logger:
  dir: "" # Имя каталога, в котором будут храниться логи. Если поле пустое, логи выводятся в os.Stdout

archiver:
  max_tasks: 3 # Максимальное количество задач (task), которые могут существовать одновременно
  max_objects: 3 # Максимальное количество объектов в задаче, запускающих архивацию
  valid_extension: # Допустимые расширения файлов, которые проверяются перед добавлением в задачу. Если конфиг пустой, то проверка не производится
    - ".pdf"
    - ".jpg"
    - ".jpeg"
  archive_object_getter:
    valid_content_type: # Допустимые типы контента, которые проверяются на этапе «Архивация» во время загрузки файла. Если конфиг пустой, то проверка не производится
    # - "application/pdf"
    # - "image/jpeg"

local_zip_storage:
  dir: "zips" # Имя каталога, в котором будут храниться конечные zip-архивы

http_server:
  addr: "localhost:8080"
  idle_timeout: 30s
