logger:
  dir: "" # The name of the directory where the logs will be stored, if the field is empty, the logs are output to os.Stdout

archiver:
  max_tasks: 3 # The maximum number of tasks that can exist simultaneously
  max_objects: 3 # Number of objects in the task that trigger archiving
  valid_extension: # Valid extensions that are checked before being added to a task, if empty then it does not validate
    - ".pdf"
    - ".jpg"
    - ".jpeg"
  archive_object_getter:
    valid_content_type: # Valid content types that are checked at the "Archiving" stage during file downloading, if empty then it does not validate
    # - "application/pdf"
    # - "image/jpeg"

local_zip_storage:
  dir: "zips" # The name of the directory in which the final zip archives will be stored

http_server:
  addr: "localhost:8080"
  idle_timeout: 30s
