logger:
  dir: "" # If the field is empty, the logs are output to os.Stdout

archiver:
  max_tasks: 3
  max_objects: 3
  valid_extension: # if empty then it does not validate
    - ".pdf"
    - ".jpg"
    - ".jpeg"
  archive_object_getter:
    valid_content_type: # if empty then it does not validate
    # - "application/pdf"
    # - "image/jpeg"

local_zip_storage:
  dir: "zips"

http_server:
  addr: "localhost:8080"
  idle_timeout: 30s
