logger:
  dir: "" # os.Stdout

archiver:
  max_tasks: 3
  max_objects: 3
  valid_extension:
    - ".pdf"
    - ".jpg"
    - ".jpeg"
  archive_object_getter:
    valid_content_type: # not validate

local_zip_storage:
  dir: "zips"

http_server:
  addr: "localhost:8080"
  idle_timeout: 30s
